# Generated by Django 4.1.7 on 2023-02-18 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posted_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
